language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-25
    - add-on
    - extra-android-m2repository

script:
   - chmod a+x gradlew
   - ./gradlew assemble